#!/usr/bin/env sh

# This script automatically changes my screen temperature if its after 10pm and sends a notification for me to get up
# Dependencies: libnotify, sct

if [ `date +%H` -ge 22 ]; then
    sct 3000
fi

notify-send "Get up, get water, stretch and look at something 20 feet away"
