#!/usr/bin/env bash

# This scripts helps me to take screenshots and record my desktop.
# Dependencies: bemenu, slurp, grim 
# Currently screen recording on Wayland doesn't work

declare -a options=(
"Record desktop"
"Screenshot"
"Stop screen recording"
)

choice=$(printf '%s\n' "${options[@]}" | bemenu -i -p 'Choose script:')

if [ "$choice" = "Screenshot" ]; then 
    geometry=$(slurp)
    notify-send "Screenshot in 3 seconds..."
    rm -rf $HOME/stuff/screen.png
    sleep 3
    grim -g "$geometry" - > $HOME/stuff/screen.png
    notify-send "Screenshot taken!"
    read -r W H <<< $(identify -format "%w %h\n" ~/stuff/screen.png)
    if [ "$W" -gt "300" ] || [ "$H" -gt "300" ]; then
        pqiv ~/stuff/screen.png -z 0.45 &
    else 
        pqiv ~/stuff/screen.png &
    fi 
    sleep 3
    pkill pqiv 
elif [ "$choice" = "Record desktop" ]; then
    slop=$(slop -f "%x %y %w %h %g %i") || exit 1
    read -r X Y W H G ID < <(echo $slop)
    rm -rf $HOME/stuff/screen.mp4
    notify-send "Screen recording in 3 seconds..."
    sleep 3
    notify-send "Screen recording started"
    ffmpeg -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y $HOME/stuff/screen.mp4 &> /dev/null
    notify-send "Screen recording finished"
elif [ "$choice" = "Stop screen recording" ]; then
    pkill ffmpeg
    notify-send "Screen recording finished"
else 
    exit 1
fi
